layout_spectrum: 0.7132684
typography_spectrum: 0.9541583
color:
  saturation: 0.793669
  lightness: 0.3519895
  brandStrength: 0.8055942
  rhythmicContrast: 0.472072
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: '13'
